oxc-project/eslint-plugin-oxlint

README.md
index.cjs
index.js

feat: support legacy config

---

.github/workflows/test.yml
README.md
index.cjs
index.js

This fixes flat config usage that was broken by my last change -- sorry.
```
✖ eslint:
Oops! Something went wrong! :(
ESLint: 8.56.0
Error: Unexpected key "configs" found.
```
New usage mimics the one of eslint-plugin-unicorn, with 2 exported configs: "flat/recommended" and "recommended".
Also i'm adding a GHA workflow that simply runs a `pnpm lint`, as a "smoke test" to validate further changes. It would have prevented the regression.

fix flat config support

---

.github/dependabot.yml
.github/workflows/dependabot.yml

- Enables Dependabot
- Whenever Dependabot updates oxlint, generate rules and push to the same branch.
Test run:

chore: use dependabot to bump oxlint rules

---

.github/dependabot.yml
.github/workflows/dependabot.yml
.github/workflows/release.yml

- To programmatically advertise that we bumped oxlint, we need to use the "increase" statregy so a user's package manager nows that we need a specific oxlint version and can optimistically fetch it.

chore(ci): fix dependabot support for oxlint bump

---

package.json

The package currently publishes all files, as no `"files"` field is specified in package.json.
This PR changes the package to only publish `lib`, `src`, `LICENSE`, `package.json`, and `README.md`.
See reference here: https://docs.npmjs.com/cli/v10/configuring-npm/package-json#files

fix: specify published directories in package.json

---

package.json

Running publint on this package generates errors regarding the order of `"exports"` fields: https://publint.dev/eslint-plugin-oxlint@0.5.0
This PR moves the `"types"` field to the first position in each export path, fixing these errors.

fix: move "types" export condition

---

.github/workflows/release.yml

This job should not have run: https://github.com/oxc-project/eslint-plugin-oxlint/actions/runs/10327248826/job/28592123359
I accidentally put quotes around the [contains](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/expressions#contains) function in #131 - however, removing them generates a YAML error with the colon in `'release: v'` (`"release: v"` also fails). A workaround is to use the [startsWith](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/expressions#startswith) function.

ci: fix release workflow condition

---

src/index.ts
src/utils.ts

we can have a rule set name while inspect eslint config by `npx eslint --inspect-config`

feat: add config name for better debug

---

.github/workflows/bump_oxlint.yml
.github/workflows/format.yml
.github/workflows/lint.yml
.prettierignore
eslint.config.js

chore(ci): improve pull request and bump oxlint jobs

---

src/utils.ts

Sadly the output does not includes the rules at the moment:
```ts
declare const _default: {
configs: {
"flat/perf": {
name: string;
rules: Record<string, string>;
};
"flat/pedantic": {
name: string;
rules: Record<string, string>;
};
"flat/nursery": {
name: string;
rules: Record<string, string>;
};
.....
```
Next plan: Updating generator script to support flat config out of the box.
This should also improve the ts definitions for them. My "dirty" fix does not work correctly:
<details><summary>Details</summary>
<p>
```ts
import { kebabCase } from 'scule';
import type { KebabCase } from 'scule';
type WithoutRulesSuffix<T> = T extends `${infer P}Rules` ? P : never;
type StringKeys<objType extends {}> = Array<Extract<keyof objType, string>>;
function replaceRulesSuffix<T extends string>(val: …
```

feat(build): add flat configs by scope and by category to index.d.ts

---

package.json
pnpm-lock.yaml

because we removed utils.ts, `scule` is only used in the generator code.

chore(deps): move scule to devDependencies

---

.github/renovate.json

Because we update eslint  to v9 in #170 we can tell renovate to update it again. Hopefully without BC this time^^

chore(ci): allow renovate to update eslint

---

src/index.ts

closes #189 
also followed the naming conventions: https://eslint.org/docs/latest/use/configure/configuration-files#configuration-naming-conventions

fix: invalid name in eslint v8

---

scripts/traverse-rules.test.ts
scripts/traverse-rules.ts

Fixes #195
The configs needs to be re-generated after this change.

fix(traverse): should correctly parse rules with fixability metadata

---

.github/workflows/bump_oxlint.yml
scripts/generate.ts

closes #198 
Reason: the generate script already bumped the version in the package file. `npm version v0.10.3` did not detect a file change, so it failed.
So we let now the CI manage the package version. Also I made it clearer what happens in the CI

fix(ci): do not bump version on generate, let CI manage it

---

scripts/config-generator.ts
scripts/generate.ts
scripts/rules-generator.test.ts
scripts/rules-generator.ts

it is only used for output. after #204 the output does not match always the cloned version

refactor: remove oxlint version from generator

---

.github/workflows/bump_oxlint.yml

this allows us to run manually this job with older version of `oxlint`.
Expected that `inputs.version` is a string in this format: `0.10.3`.
After this merge we can, if we want, create an release `0.10.2` and not get the changes from `0.10.3`

ci: improve bump_oxlint, force right version

---

package.json

This change addresses an issue where VSCode (1.9X) could not locate the TypeScript declaration file, resulting in a "Cannot find module "eslint-plugin-oxlint" ts(2307)" error. Adding `"types": "./dist/index.d.ts"` to `package.json` ensures that TypeScript definitions are correctly referenced, enhancing editor support and avoiding import errors in TypeScript projects.

fix: add missing types entry in package.json

---

scripts/constants.ts
scripts/traverse-rules.ts
src/__snapshots__/configs.spec.ts.snap
src/build-from-oxlint-config.spec.ts
src/build-from-oxlint-config.ts
src/generated/configs-by-scope.ts
src/generated/rules-by-category.ts
src/generated/rules-by-scope.ts

fix: put `react-hooks` plugin rules into own scope and not under `react`

---

README.md
scripts/constants.ts
scripts/traverse-rules.ts
src/__snapshots__/build-from-oxlint-config.spec.ts.snap
src/__snapshots__/configs.spec.ts.snap
src/build-from-oxlint-config.spec.ts
src/generated/configs-by-category.ts
src/generated/configs-by-scope.ts
src/generated/rules-by-category.ts
src/generated/rules-by-scope.ts

**BREAKING CHANGE:** The Configuration `oxlint.configs['flat/nursery']` does not exist anymore.
The function `buildFromOxlint` will also ignore this category from now on.

fix!: ignore nursery rules

---

package.json

closes #312 
> package.json was not found: Package subpath './package.json' is not defined by "exports"
Some tools like to look into our package.json but we are not currently allowing it.

fix: add `package.json` to the package exports 

---

src/build-from-oxlint-config/rules.ts

fix: do not output warning when no matching oxlint rule is found

---

.github/renovate.json
package.json
pnpm-lock.yaml

see reasons here: https://github.com/oxc-project/oxc-node/issues/109

chore(deps): ignore updates for @oxc-node/core and downgrade to 0.0.22

---

src/build-from-oxlint-config/categories.ts
src/build-from-oxlint-config/extends.spec.ts
src/build-from-oxlint-config/extends.ts
src/build-from-oxlint-config/index.ts
src/build-from-oxlint-config/plugins.ts
src/build-from-oxlint-config/types.ts
src/build-from-oxlint-config/utilities.ts

This PR introduces an initial implementation to support the extends property in configuration files and follow the full chain of extended files.
Currently, it handles merging of only the following fields:
- `rules`
- `plugins`
- `overrides`
These are the only fields currently supported by oxlint, and it doesn’t appear necessary to support others at this stage.
Fixes #386

feat: support extends configuration from oxlint config content

---

package.json

Running `npm pack` on main:
```
npm notice package size: 44.6 kB
npm notice unpacked size: 249.3 kB
```
After:
```
npm notice package size: 35.5 kB
npm notice unpacked size: 194.2 kB
```

chore(npm): do not publish test files
